SpartaMissionX/QuestLoggers

- .gitignore
- src/main/java/com/missionx/questloggers/domain/comment/controller/CommentController.java
- src/main/java/com/missionx/questloggers/domain/comment/dto/CreateCommentRequestDto.java
- src/main/java/com/missionx/questloggers/domain/comment/dto/CreateCommentResponseDto.java
- src/main/java/com/missionx/questloggers/domain/comment/dto/Dto.java
- src/main/java/com/missionx/questloggers/domain/comment/entity/Comment.java
- src/main/java/com/missionx/questloggers/domain/comment/service/CommentService.java
- src/main/java/com/missionx/questloggers/domain/post/entity/Post.java
- src/main/java/com/missionx/questloggers/domain/post/exception/NotFoundException.java
- src/main/java/com/missionx/questloggers/domain/post/exception/PostException.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
- src/main/java/com/missionx/questloggers/domain/user/entity/User.java
- src/main/java/com/missionx/questloggers/domain/user/service/UserService.java
- src/main/java/com/missionx/questloggers/global/entity/BaseEntity.java
- Comment 생성 API 구현 
- .env 파일 커핏에 안뜨도록 변경
- BaseEntity 내용 수정
-
> feat : Comment 생성 API 구현

- src/main/java/com/missionx/questloggers/domain/post/controller/PostController.java
- src/main/java/com/missionx/questloggers/domain/post/dto/CreatePostRequestDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/CreatePostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/Dto.java
- src/main/java/com/missionx/questloggers/domain/post/entity/Post.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
-포스트 생성 API 완
- JWT 구현 후 적용해야함
> leh PostCreate comple

- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
> bugfix: 컴파일 오류 해결

- src/main/java/com/missionx/questloggers/domain/comment/controller/CommentController.java
- src/main/java/com/missionx/questloggers/domain/comment/service/CommentService.java
- src/main/java/com/missionx/questloggers/global/entity/BaseEntity.java
- 댓글 삭제 기능 추가
- BaseEntity Delete기능 추가
-
> feat: 댓글 삭제 기능 추가

- src/main/java/com/missionx/questloggers/domain/character/controller/CharacterController.java
- src/main/java/com/missionx/questloggers/domain/character/dto/AccountListDto.java
- src/main/java/com/missionx/questloggers/domain/character/dto/CharacterDto.java
- src/main/java/com/missionx/questloggers/domain/character/dto/CreateCharacterResponseDto.java
- src/main/java/com/missionx/questloggers/domain/character/dto/Dto.java
- src/main/java/com/missionx/questloggers/domain/character/entity/Character.java
- src/main/java/com/missionx/questloggers/domain/character/enums/WorldName.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
- src/main/java/com/missionx/questloggers/global/config/RestTemplateConfig.java
- src/main/java/com/missionx/questloggers/global/config/config.java
-Character 생성 api , 조회 api 추가
-
> feat : Character 생성 api , 조회 api 추가

- src/main/java/com/missionx/questloggers/domain/character/controller/CharacterController.java
- src/main/java/com/missionx/questloggers/domain/character/dto/SerchAllCharResponseDto.java
- src/main/java/com/missionx/questloggers/domain/character/dto/SerchCharResponseDto.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
> leh 캐릭터 정보 검색 API 완 (테스트 못해봄)

- src/main/java/com/missionx/questloggers/domain/character/controller/CharacterController.java
- src/main/java/com/missionx/questloggers/domain/character/dto/UpdateOwnerCharResponseDte.java
- src/main/java/com/missionx/questloggers/domain/character/repository/CharacterRepository.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
> 대표캐릭터 변경 API

- build.gradle
- src/main/java/com/missionx/questloggers/domain/auth/service/AuthService.java
- src/main/java/com/missionx/questloggers/domain/comment/controller/CommentController.java
- src/main/java/com/missionx/questloggers/domain/comment/exception/UnauthorizedCommentAccessException.java
- src/main/java/com/missionx/questloggers/domain/comment/service/CommentService.java
- src/main/java/com/missionx/questloggers/domain/post/controller/PostController.java
- src/main/java/com/missionx/questloggers/domain/post/exception/UnauthorizedPostAccessException.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
- src/main/java/com/missionx/questloggers/domain/user/controller/UserController.java
- src/main/java/com/missionx/questloggers/domain/user/dto/UpdatePasswordRequestDto.java
- src/main/java/com/missionx/questloggers/domain/user/dto/UpdatePasswordResponseDto.java
- src/main/java/com/missionx/questloggers/domain/user/entity/User.java
- src/main/java/com/missionx/questloggers/domain/user/service/UserService.java
- src/main/java/com/missionx/questloggers/global/config/JwtAuthorizationFilter.java
- src/main/java/com/missionx/questloggers/global/config/JwtTokenProvider.java
- src/main/java/com/missionx/questloggers/global/config/SecurityConfig.java
- src/main/java/com/missionx/questloggers/global/config/security/LoginUser.java
- src/main/java/com/missionx/questloggers/global/exception/GlobalExceptionHandler.java
- src/main/resources/application.yml
- Role 필드 Enum -> String 으로 타입 변경 (변경된 db 설명 예정)
- JWT토큰 playlod 추가
- spring security 인가 처리 고도화
- 비밀번호 변경 시 jwt 토큰 재발급(내일 오전중으로 redis 기반 로그아웃처리 예정)
- 게시글, 댓글 예외처리 요망(테스트..)
- redis 기반 로그아웃 처리
- 회원탈퇴시 jwt토큰 무효화
> Auth 기능들 보완

- src/main/java/com/missionx/questloggers/domain/auth/service/AuthService.java
- src/main/java/com/missionx/questloggers/domain/character/controller/CharacterController.java
- src/main/java/com/missionx/questloggers/domain/character/dto/CharacterListRespnseDto.java
- src/main/java/com/missionx/questloggers/domain/character/repository/CharacterRepository.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
- src/main/java/com/missionx/questloggers/domain/characterboss/service/CharacterBossService.java
> 캐릭터 조회 API 수정 , 회원가입시 캐릭터 자동 생성되도록 수정

- src/main/java/com/missionx/questloggers/domain/auth/exception/AuthException.java
- src/main/java/com/missionx/questloggers/domain/auth/exception/ExpiredTokenException.java
- src/main/java/com/missionx/questloggers/domain/auth/exception/MalformedTokenException.java
- src/main/java/com/missionx/questloggers/domain/auth/exception/NoneTokenException.java
- src/main/java/com/missionx/questloggers/global/config/JwtAuthorizationFilter.java
- src/main/java/com/missionx/questloggers/global/config/JwtTokenProvider.java
- src/main/java/com/missionx/questloggers/global/exception/GlobalExceptionHandler.java
- refactor : 예외처리 수정 및 필터 수정
- 필터 내부 예외는 globalexceptionhandler에서 작동x 
- security filterchain -> jwt filter -> dispatcherservlet -> 예외발생 -> globalexceptionhandler 처리
> refactor : 예외처리 수정 및 필터 수정

- src/main/java/com/missionx/questloggers/domain/boss/controller/BossController.java
- src/main/java/com/missionx/questloggers/domain/character/controller/CharacterController.java
- src/main/java/com/missionx/questloggers/domain/character/dto/GetOwnerCharResponseDto.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
- src/main/java/com/missionx/questloggers/domain/characterboss/controller/CharacterBossController.java
- src/main/java/com/missionx/questloggers/domain/characterboss/service/CharacterBossService.java
- src/main/java/com/missionx/questloggers/domain/user/entity/User.java
- src/main/java/com/missionx/questloggers/global/config/JwtTokenProvider.java
-
로그인한 유저의 대표 캐릭터가
클리어정보 조회 , 보스 생성, 클리어 여부 수정 할 수 있도록 변경
-
> CharacterBoss 수정

- src/main/java/com/missionx/questloggers/domain/user/entity/User.java
- src/main/java/com/missionx/questloggers/domain/user/repository/UserRepository.java
- src/main/java/com/missionx/questloggers/domain/user/service/UserService.java
- src/main/java/com/missionx/questloggers/global/config/JwtAuthorizationFilter.java
> refactor : User

- src/main/java/com/missionx/questloggers/domain/character/dto/CharacterListRespnseDto.java
- src/main/java/com/missionx/questloggers/domain/character/dto/SearchAllCharResponseDto.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
- src/main/java/com/missionx/questloggers/domain/comment/service/CommentService.java
- src/main/java/com/missionx/questloggers/domain/user/dto/FindUserResponseDto.java
- src/main/java/com/missionx/questloggers/domain/user/service/UserService.java
> 2차 내부검수 수정사항 수정

- .env
- .gitignore
- src/main/java/com/missionx/questloggers/domain/user/repository/UserRepository.java
- src/main/java/com/missionx/questloggers/domain/user/service/UserService.java
> 회원탈퇴 hard delete로 수정

- .github/workflows/cicd deploy.yml
> leh cicd 디플로이 Upload JAR Artifact 경로 수정

- src/main/java/com/missionx/questloggers/domain/post/controller/PostController.java
- src/main/java/com/missionx/questloggers/domain/post/dto/ApplyPartyResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/CreatePostRequestDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/CreatePostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/GetAllPostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/GetPostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/UpdatePostRequestDto.java
- src/main/java/com/missionx/questloggers/domain/post/dto/UpdatePostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/entity/PartyApplicant.java
- src/main/java/com/missionx/questloggers/domain/post/entity/Post.java
- src/main/java/com/missionx/questloggers/domain/post/enums/ApplicantStatus.java
- src/main/java/com/missionx/questloggers/domain/post/enums/Difficulty.java
- src/main/java/com/missionx/questloggers/domain/post/enums/PartySize.java
- src/main/java/com/missionx/questloggers/domain/post/exception/InvalidPartyActionException.java
- src/main/java/com/missionx/questloggers/domain/post/repository/PartyApplicantRepository.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
- src/main/java/com/missionx/questloggers/global/exception/GlobalExceptionHandler.java
- src/main/resources/application-local.yml
> 파티원 신청 API

- src/main/java/com/missionx/questloggers/domain/comment/service/CommentService.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostSupporService.java
Postservice 내 findById 기능
PostSupporService 내 기능 활용하도록 수정
-
-
> Postservice 내 findById 기능 PostSupporService 내 기능 활용하도록 수정

- src/main/java/com/missionx/questloggers/domain/character/controller/CharacterController.java
- src/main/java/com/missionx/questloggers/domain/character/dto/SetOwnerCharRequestDto.java
- src/main/java/com/missionx/questloggers/domain/character/service/CharacterService.java
- src/main/java/com/missionx/questloggers/domain/partyapplicant/entity/PartyApplicant.java
- src/main/java/com/missionx/questloggers/domain/partyapplicant/enums/ApplicantStatus.java
- src/main/java/com/missionx/questloggers/domain/partyapplicant/repository/PartyApplicantRepository.java
- src/main/java/com/missionx/questloggers/domain/partyapplicant/service/PartyApplicantSupportService.java
- src/main/java/com/missionx/questloggers/domain/partymember/dto/PartyMemberResponseDto.java
- src/main/java/com/missionx/questloggers/domain/partymember/enums/ApplicantStatus.java
- src/main/java/com/missionx/questloggers/domain/partymember/repository/PartyMemberRepository.java
- src/main/java/com/missionx/questloggers/domain/partymember/service/PartyMemberSupportService.java
- src/main/java/com/missionx/questloggers/domain/post/controller/PostController.java
- src/main/java/com/missionx/questloggers/domain/post/dto/PartyApplicantResponseDto.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
> 파티원 신청 수락 , 거절, 파티원목록조회 api 구현

- src/main/java/com/missionx/questloggers/domain/partyapplicant/service/PartyApplicantSupportService.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
- 파티 신청수 최대인원을 넘겨도 신청되던 버그를 수정함
-
> leh 파티 최대 신청인원수 제한 버그 수정

- src/main/java/com/missionx/questloggers/domain/partyapplicant/repository/PartyApplicantRepository.java
- src/main/java/com/missionx/questloggers/domain/partyapplicant/service/PartyApplicantSupportService.java
- src/main/java/com/missionx/questloggers/domain/post/controller/PostController.java
- src/main/java/com/missionx/questloggers/domain/test/character/TestCharController.java
- src/main/java/com/missionx/questloggers/domain/test/character/TestCharacterService.java
- src/main/java/com/missionx/questloggers/domain/test/party/TestApplyPartyController.java
- src/main/java/com/missionx/questloggers/domain/test/party/TestApplyPartyService.java
- src/main/java/com/missionx/questloggers/domain/test/thread/TestApplyParty.java
- src/main/java/com/missionx/questloggers/global/config/JwtAuthorizationFilter.java
- src/main/java/com/missionx/questloggers/global/config/SecurityConfig.java
- 파티 최대 신청인원수 제한 버그 수정 및 테스트 컨트롤러 완성
-
> leh 파티 최대 신청인원수 제한 버그 수정 및 테스트 컨트롤러 완성

- build.gradle
- src/main/java/com/missionx/questloggers/QuestLoggersApplication.java
- src/main/java/com/missionx/questloggers/domain/tip/controller/TipPostController.java
- src/main/java/com/missionx/questloggers/domain/tip/dto/CreateTipPostRequestDto.java
- src/main/java/com/missionx/questloggers/domain/tip/dto/CreateTipPostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/tip/dto/GetAllTipPostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/tip/dto/GetTipPostResponseDto.java
- src/main/java/com/missionx/questloggers/domain/tip/entity/TipPost.java
- src/main/java/com/missionx/questloggers/domain/tip/exception/TipNotFoundException.java
- src/main/java/com/missionx/questloggers/domain/tip/repository/TipPostRepository.java
- src/main/java/com/missionx/questloggers/domain/tip/service/TipPostService.java
- src/main/java/com/missionx/questloggers/global/config/cache/CacheConfig.java
- src/main/java/com/missionx/questloggers/global/config/cache/CacheType.java
- src/main/resources/application.yml
> 캐싱관련 구현, 오류 수정

- src/main/java/com/missionx/questloggers/domain/notification/controller/SseEmitterController.java
- src/main/java/com/missionx/questloggers/domain/notification/dto/GetPartyApplicantsResponseDto.java
- src/main/java/com/missionx/questloggers/domain/notification/dto/PartyApplicantDto.java
- src/main/java/com/missionx/questloggers/domain/notification/entity/Notification.java
- src/main/java/com/missionx/questloggers/domain/notification/enums/NotificationStatus.java
- src/main/java/com/missionx/questloggers/domain/notification/repository/NotificationRepository.java
- src/main/java/com/missionx/questloggers/domain/notification/service/NotificationService.java
- src/main/java/com/missionx/questloggers/domain/notification/service/NotificationSupportService.java
- src/main/java/com/missionx/questloggers/domain/notification/service/SseEmiterService.java
- src/main/java/com/missionx/questloggers/domain/notification/service/SseEmitterService.java
- src/main/java/com/missionx/questloggers/domain/partyapplicant/service/PartyApplicantSupportService.java
- src/main/java/com/missionx/questloggers/domain/post/controller/PostController.java
- src/main/java/com/missionx/questloggers/domain/post/service/PostService.java
> 파티 신청 , 승인 , 거절 , 탈퇴 , 강퇴 기능에 알림 발송

- build.gradle
- src/main/java/com/missionx/questloggers/domain/tip/service/TipPostService.java
- src/main/java/com/missionx/questloggers/global/config/cache/CacheConfig.java
- src/main/resources/application.yml
> refactor : 직렬화 문제 수정

- src/main/resources/application.yml
> refactor : 환경변수 수정

- build.gradle
- src/main/java/com/missionx/questloggers/domain/test/thread/TestApplyParty.java
- src/main/java/com/missionx/questloggers/global/config/JwtAuthorizationFilter.java
- src/main/java/com/missionx/questloggers/global/config/SecurityConfig.java
- src/main/resources/application-prod.yml
> leh 스프링 헬스체크를 위한 전반적인 수정
